### ISSUE TITLE
using docker, cannot connect to hive, not log other logs , where can I see the client source code and debug 

### ISSUE THREAD

**Issue by hellozeck** [hyperspaceai/aios-cli#7]
![image](https://github.com/user-attachments/assets/65f31d4b-383e-4d57-90fc-2c5d518fb914)

**Comment by hellozeck** [comment]
need to run disconnect first

**Comment by markanopko22** [comment]
Can u link me a guide on docker?

> ![image](https://github.com/user-attachments/assets/65f31d4b-383e-4d57-90fc-2c5d518fb914)
